# -*- coding: utf-8 -*-
"""
/***************************************************************************
 layer_style_master
                                 A QGIS plugin
 This QGIS plugin copies symbology, labels, and rendering settings from one layer to multiple other layers.

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-08-27
        copyright            : (C) 2024 by Dr. Ahmad Sahraei Juybari
        email                : ahmad.sahraeijuybari@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Dr. Ahmad Sahraei Juybari'
__date__ = '2024-08-27'
__copyright__ = '(C) 2024 by Dr. Ahmad Sahraei Juybari'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load layer_style_master class from file layer_style_master.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .layer_style_master import layer_style_masterPlugin
    return layer_style_masterPlugin()
