# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerStyleMaster
                                 A QGIS plugin
 This QGIS plugin copies symbology, labels, and rendering settings from one layer to multiple other layers.


 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-09-10
        copyright            : (C) 2024 by Dr.-Ing. Ahmad Sahraei Juybari
        email                : ahmad.sahraeijuybari@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Dr.-Ing. Ahmad Sahraei Juybari'
__date__ = '2024-09-10'
__copyright__ = '(C) 2024 by Dr.-Ing. Ahmad Sahraei Juybari'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayerStyleMaster class from file LayerStyleMaster.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Layer Style Master import LayerStyleMasterPlugin
    return LayerStyleMasterPlugin()
