# -*- coding: utf-8 -*-

"""
/***************************************************************************
 LayerStyleMaster
                                 A QGIS plugin
 This QGIS plugin copies symbology, labels, and rendering settings from one layer to multiple other layers.


 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-09-10
        copyright            : (C) 2024 by Dr.-Ing. Ahmad Sahraei Juybari
        email                : ahmad.sahraeijuybari@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Dr.-Ing. Ahmad Sahraei Juybari'
__date__ = '2024-09-10'
__copyright__ = '(C) 2024 by Dr.-Ing. Ahmad Sahraei Juybari'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .Layer Style Master_provider import LayerStyleMasterProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class LayerStyleMasterPlugin(object):

    def __init__(self):
        self.provider = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = LayerStyleMasterProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
